### ISSUE TITLE
Support (or sugar? or nothing?) for PostgreSQL's composite types

### ISSUE THREAD

**Issue by icassina** [tpolecat/doobie#94] opened 2015-02-14 16:12 UTC
PostgreSQL supports user-defined types.

Type creation is easily done with:
```
CREATE TYPE Point2D AS (x NUMERIC, y NUMERIC);
```

Value construction is done using 'ROW':
```
SELECT (ROW(10, 22.2) :: Point2D) AS point 
```

Value deconstruction is done using '.':
```
SELECT (ROW(10, 22.2) :: Point2D).x
```

**Comment by icassina** [comment] 2015-02-14 16:17
Enumeration would be very nice too:

Type creation:
```
CREATE Trool AS ENUM ('True', 'False', 'DontCare');
```

Value construction is nobrain:
```
SELECT ('True' :: Trool)
```

But value must be valid:

```
SELECT ('Bad' :: Trool)
```
> ERROR:  invalid input value for enum trool: "Bad"
> LINE 1: SELECT 'Bad'::Trool;

**Comment by tpolecat** [comment] 2015-02-14 17:56
Yes, this is in the works, probably not for 0.2.1 but for the next version.

Duplicate of #49, kind of. I will combine them later.

**Comment by tpolecat** [comment] 2015-02-15 04:49
@icassina I'm closing this with links to related issues above. Please feel free to add comments to those.

**Closed by tpolecat** 2015-02-15 04:49 UTC
Labels: enhancement
