### ISSUE TITLE
java.lang.StackOverflowError when large list is passed to Fragments.in()

### ISSUE THREAD

**Issue by unoexperto** [tpolecat/doobie#485] opened 2017-03-15 18:36 UTC
I get `StackOverflowError` when large list is passed to `Fragments.in()`

Looks like it's result of recursive call in `doobie.util.composite.zip()` in line `val set = .....`

I know it's bad practice to pass so many params to `IN` clause but for situations where performance is critical it would be great if doobie can be just slow but not crash the process.

Thanks!

**Comment by tpolecat** [comment] 2017-03-16 04:52
Can you attach a stacktrace that shows the cycle?

**Comment by unoexperto** [comment] 2017-03-16 06:03
Sure.

![image](https://cloud.githubusercontent.com/assets/1280853/23983833/54c89204-0a27-11e7-83fc-6f6ee9d553d6.png)

```
Uncaught error from thread [default-akka.actor.default-dispatcher-21] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[default]
java.lang.StackOverflowError
	at doobie.util.composite$Composite$$anon$3$$anonfun$5.apply(composite.scala:56)
	at doobie.util.composite$Composite$$anon$3$$anonfun$5.apply(composite.scala:56)
	at doobie.util.composite$Composite$$anon$3$$anonfun$5.apply(composite.scala:56)
	at doobie.util.composite$Composite$$anon$3$$anonfun$5.apply(composite.scala:56)
	at doobie.util.composite$Composite$$anon$3$$anonfun$5.apply(composite.scala:56)
	at doobie.util.composite$Composite$$anon$3$$anonfun$5.apply(composite.scala:56)
	at doobie.util.composite$Composite$$anon$3$$anonfun$5.apply(composite.scala:56)
	at doobie.util.composite$Composite$$anon$3$$anonfun$5.apply(composite.scala:56)
	at doobie.util.composite$Composite$$anon$3$$anonfun$5.apply(composite.scala:56)
	at doobie.util.composite$Composite$$anon$3$$anonfun$5.apply(composite.scala:56)
	at doobie.util.composite$Composite$$anon$3$$anonfun$5.apply(composite.scala:56)
	at doobie.util.composite$Composite$$anon$3$$anonfun$5.apply(composite.scala:56)
	at doobie.util.composite$Composite$$anon$3$$anonfun$5.apply(composite.scala:56)
	at doobie.util.composite$Composite$$anon$3$$anonfun$5.apply(composite.scala:56)
	at doobie.util.composite$Composite$$anon$3$$anonfun$5.apply(composite.scala:56)

```

**Comment by fanf** [comment] 2017-03-17 22:38
Seems related to #426

**Comment by tpolecat** [comment] 2018-04-11 03:59
(duplicate of #426)

**Closed by tpolecat** 2018-04-11 03:59 UTC
