### ISSUE TITLE
new date issue in latest h2

### ISSUE THREAD

**Issue by tpolecat** [tpolecat/doobie#1070] opened 2019-11-13 20:01 UTC
dates are getting parsed in a timezone, looks like

https://github.com/tpolecat/doobie/pull/1069/files#diff-b430b84e498e097bc391705fedeb983d

**Comment by zsambek** [comment] 2019-12-12 22:22
@tpolecat After a bit of searching, I have found out that the tests are only failing when the date is before 1900. The tests are succeeding with dates that are after 1900. 
I went to the h2database's Issue page and found an issue regarding this (h2database/h2database/issues/2261). 

What I could not understand if this is caused by the java.sql.Date, then why is this test succeeding?

https://github.com/tpolecat/doobie/blob/c97012df28f3afb67f56426d42f01069af1a14b7/modules/h2/src/test/scala/doobie/h2/h2types.scala#L68

**Comment by tpolecat** [comment] 2019-12-12 22:30
Cool, thanks for the clue.

**Comment by zsambek** [comment] 2019-12-13 08:05
The above test is only succeeding because java.sql.Date(4,5,6) is converted to 1904-06-06. 
If we change the test to
```testInOut[java.sql.Date]("DATE", java.sql.Date.valueOf(java.time.LocalDate.of(4,5,6)))```
then it fails.

**Comment by zsambek** [comment] 2019-12-13 13:19
Based on @katzyn comment, they are no longer supporting java.sql.Date. 
To be honest I do not really know why the getDate function is not marked as deprecated if this is the case.
Since doobie also uses java.sql.Date for java.util.Date it is also failing for dates before 1890-10-01.

**Comment by katzyn** [comment] 2019-12-13 14:23
Legacy datetime API in Java has known bugs for decades that weren't fixed in time by Sun and most likely aren't going to be fixed by OpenJDK community, especially when Java 8 was released in 2014 and all projects had enough time to migrate to JSR-310 datetime API. Actually there is no way to fix all problems in `java.sql.Date`, `java.sql.Time`, and `java.sql.Timestamp`. Issue with LMT that you see can be fixed in Java, but some other issues are caused by bugs in design and there was no way to fix them without a new API.

Just don't use that stuff. Use `PreparedStatement.setObject(LocalDate)` and `ResultSet.getObject(column, LocalDate.class)` and `java.time.LocalDate` instead.

H2 still supports legacy datetime classes, but only under conditions when own bugs of Java don't appear.

https://h2database.com/html/datatypes.html#date_type
> If your time zone had LMT (local mean time) in the past and you use such old dates (depends on the time zone, usually 100 or more years ago), don't use java.sql.Date to read and write them.
>
> If you deal with very old dates (before 1582-10-15) note that java.sql.Date uses a mixed Julian/Gregorian calendar, java.util.GregorianCalendar can be configured to proleptic Gregorian with setGregorianChange(new java.util.Date(Long.MIN_VALUE)) and used to read or write fields of dates.

**Comment by tpolecat** [comment] 2019-12-13 15:38
Thanks, that's helpful. It's hard to know what to do in general because JDBC only supports `Date` and `Timestamp` and doobie is just a JDBC wrapper. It might make sense to remove default support for those data types and rely on vendor-specific mappings.

**Comment by katzyn** [comment] 2019-12-13 15:50
> because JDBC only supports Date and Timestamp and doobie is just a JDBC wrapper

That isn't true, `java.time.LocaDate`, `java.time.LocalTime`, `java.time.LocalDateTime`, `java.time.OffsetTime`, and `java.time.OffsetDateTime` are supported since JDBC 4.2 (Java 8). They simply don't have new own methods, because in JDBC 4.1 (Java 7) shared methods with generics for any classes were introduced.

Some drivers, including the H2, support different additional `java.time.*` classes from JSR-310.

**Comment by tpolecat** [comment] 2019-12-13 15:52
Oh, interesting. So those data types are supported via `set/getObject` as part of the spec now?

**Comment by katzyn** [comment] 2019-12-13 16:00
Take a look at JDBC™ 4.2 Specification or at more recent JDBC™ 4.3 Specification.

These JSR-310 classes are supported via `setObject()`, `getObject(column, LocalDateTime.class)` and similar methods.

Note that many databases don't have a full set of all 5 datetime data types from the SQL Standard (`DATE`, `TIME`, `TIMESTAMP`, `TIME WITH TIME ZONE`, `TIMESTAMP WITH TIME ZONE`) and their drivers therefore may not support all 5 datetime classes from the JDBC Specification. Latest H2 supports them all.

BTW, `TIME WITH TIME ZONE` and `TIMESTAMP WITH TIME ZONE` have only JSR-310 representations in JDBC.

**Comment by katzyn** [comment] 2019-12-13 16:03
Don't use `getObject()` without a `Class` parameter, the default mappings weren't changed. `getObject(column)` on a `DATE` column returns a legacy `java.sql.Date`, but `getObject(column, LocalDate.class)` returns a `java.time.LocalDate` and such behavior is required by the JDBC.

**Comment by tpolecat** [comment] 2019-12-13 16:04
Cool, thanks, very helpful. Will re-examine all this stuff. doobie started off on Java 6 and I haven't kept up with changes since then.

**Comment by zsambek** [comment] 2019-12-13 18:59
I gave it a shot and it worked. Thanks @katzyn.
```
/** @group Instances */
  implicit val JavaTimeLocalDateMeta: Meta[java.time.LocalDate] =
    Basic.one[java.time.LocalDate](
      Date,
      List(Char, VarChar, LongVarChar, Timestamp),
      _.getObject(_, classOf[java.time.LocalDate]),
      _.setObject(_, _),
      _.updateObject(_, _)
    )
```
@tpolecat Tomorrow if I will have time I am going to write new meta instances for JSR-310 classes.

**Comment by tpolecat** [comment] 2019-12-13 19:22
@zsambek 👍 👍  that would be great!

**Comment by zsambek** [comment] 2019-12-13 22:09
@tpolecat I think It is done. Since PG does not support every JSR-310 data type I could not implement all the tests.

**Closed** 2019-12-14 16:40 UTC
