### ISSUE TITLE
no Atom/Param instance for 1-member case classes

### ISSUE THREAD

**Issue by refried** [tpolecat/doobie#234] opened 2015-10-06 15:37 UTC
> I have a query with a parameter that is an `Int` in the database.  In my code, it's represented by `case class MeetingId(int: Int)`.  I do automatically get a `Composite[MeetingId]`, but I get the error `Could not find or construct Param[MeetingId :: HNil]` and a hint saying, "make sure you can summon an `Atom`", which I can't.  Should I be able to get one automatically from something like `MeetingId` which is isomorphic to `Int :: HNil`?

.

> @refried hm yeah that's a corner case. for now you can work around it by constructing a `Meta`
`implicit val MeetingIdMeta: Meta[MeetingId] = Meta[Int].xmap(MeetingId, _.int)` Can you open an issue for that? That's irritating.

**Comment by tpolecat** [comment] 2015-10-06 16:21
Duplicate of #12, which I will close. This has been around for a long time but was masked by #202.

**Comment by refried** [comment] 2015-10-06 18:54
Here's a version that doesn't work, by me: http://scastie.org/12459
and a version that does work, by @wedens: http://scastie.org/12463

Is there not a simpler way though?

**Comment by tpolecat** [comment] 2015-10-06 21:01
The @wedens version seems fine, but it should use `.nxmap` to deal with `null` properly.

**Closed** 2015-10-09 02:16 UTC
