### ISSUE TITLE
Literal value splicing in fragments?

### ISSUE THREAD

**Issue by longcao** [tpolecat/doobie#778] opened 2018-10-04 22:56 UTC
Currently, to splice in literal values to `Fragment`s we use `Fragment.const` and concatenation as recommended [in the guide](https://tpolecat.github.io/doobie/docs/08-Fragments.html#composing-sql-literals), which is a little less smooth than say, [what Slick offers](http://slick.lightbend.com/doc/3.2.3/sql.html#splicing-literal-values) in its plain SQL experience.

e.g, currently:
```scala
import doobie._
import doobie.implicits._
import cats.implicits._

val myTable = "my_table"
val fragment = fr"CREATE TABLE" ++ Fragment.const(myTable)
```

Maybe taking the literal syntax from Slick (would make it easier to port plain SQL usage from Slick if someone wanted to):
```scala
val myTable = "my_table"
val fragment = fr"CREATE TABLE #$myTable"
```

Perhaps it would be nice to have similar syntax in doobie, probably with the requisite warnings about injection...

![3ba](https://user-images.githubusercontent.com/865236/46507477-a47fd480-c806-11e8-9e23-f96701d5ee98.jpg)

**Comment by jatcwang** [comment] 2018-11-12 10:51
Seems to be a duplicate of https://github.com/tpolecat/doobie/issues/778 with the same suggested syntax

**Closed** 2020-01-11 04:24 UTC
