### ISSUE TITLE
Error with query from table with 70+ columns.

### ISSUE THREAD

**Issue by wpoosanguansit** [tpolecat/doobie#217] opened 2015-08-27 19:03 UTC
I do get Could not find or construct Composite[model.Table] error.  So I tried using Shapeless hlist type:

all columns:
Option[String] :: Option[String] :: Option[String] :: Option[LocalDateTime] ::
	                              Option[String] :: Option[String] :: Option[String] :: Option[String] ::
	                              Option[String] :: Option[String] :: Option[String] :: Option[String] ::
	                              Option[String] :: Option[String] :: Option[String] :: Option[String] ::
	                              Option[String] :: Option[String] :: Option[String] :: Option[String] :: 
	                              Option[String] :: Option[String] :: Option[LocalDateTime]    :: Option[LocalDateTime] :: 
	                              Option[LocalDateTime]    :: Option[LocalDateTime] :: Option[String] :: Option[String] :: 
	                              Option[String] :: Option[String] :: Option[String] :: Option[String] ::
	                              Option[String] :: Option[String] :: Option[String] :: Option[String] ::
	                              Option[String] :: Option[String] :: Option[String] :: Option[String] ::
	                              Option[String] :: Option[String] :: Option[String] :: Option[String] ::
	                              Option[String] :: Option[String] :: Option[String] :: Option[BigDecimal] :: 
	                              Option[String] :: Option[BigDecimal] :: Option[BigDecimal] ::
	                              Option[String] :: Option[String] :: Option[String] :: Option[String] ::
	                              Option[String] :: Option[String] :: Option[String] :: Option[String] ::
	                              Option[String] :: Option[String] :: Option[BigDecimal] :: Option[BigDecimal] ::
	                              Option[String] :: Option[String] :: Option[String] :: Option[String] ::
	                              Option[String] :: Option[String] :: Option[String] :: Option[String] ::
	                              Option[String] :: Option[String] :: Option[BigDecimal] :: Option[BigDecimal] ::
	                              Option[String] :: HNil
I do get this error:
Could not find or construct Composite[TableShapelessType]

But after I take out some of the columns up til the ones shown below (taking out about 25 columns), the query ran fine:

Option[String] :: Option[String] :: Option[String] :: Option[LocalDateTime] ::
	                              Option[String] :: Option[String] :: Option[String] :: Option[String] ::
	                              Option[String] :: Option[String] :: Option[String] :: Option[String] ::
	                              Option[String] :: Option[String] :: Option[String] :: Option[String] ::
	                              Option[String] :: Option[String] :: Option[String] :: Option[String] :: 
	                              Option[String] :: Option[String] :: Option[LocalDateTime]    :: Option[LocalDateTime] :: 
	                              Option[LocalDateTime]    :: Option[LocalDateTime] :: Option[String] :: Option[String] :: 
	                              Option[String] :: Option[String] :: Option[String] :: Option[String] ::
	                              Option[String] :: Option[String] :: Option[String] :: Option[String] ::
	                              Option[String] :: Option[String] :: Option[String] :: Option[String] ::
	                              Option[String] :: Option[String] :: Option[String] :: Option[String] ::
	                              Option[String] :: Option[String] :: Option[String] :: Option[BigDecimal] :: 
	                              Option[String] :: Option[BigDecimal] :: HNil

 Thanks for your help.

Added:  I am not sure if this might help.  I do keep getting Could not find or construct Composite[TableShapelessType] the more I added query functions to the test suite.  And I kept taking out one or two columns each time and things would be running fine again.  Now I am down to about 46 columns.

Also, I kept adding to my test suite for selecting data from the legacy.  I do have about 12 tests.  I could run each individually.  But I could not run more than 6 of them at the same time.  Especially those with a more complicated WHERE clauses, I could run those at most 2 or 3 at the same time.  Else I am getting this error:

The message id: as_connect_message_error With parameters: server handle not available (HPT4Messages.java:304)
[error] org.trafodion.jdbc.t4.HPT4Messages.createSQLException(HPT4Messages.java:304)
[error] org.trafodion.jdbc.t4.HPT4Messages.createSQLException(HPT4Messages.java:238)
[error] org.trafodion.jdbc.t4.InterfaceConnection.connect(InterfaceConnection.java:876)
[error] org.trafodion.jdbc.t4.InterfaceConnection.<init>(InterfaceConnection.java:173)
[error] org.trafodion.jdbc.t4.TrafT4Connection.makeConnection(TrafT4Connection.java:1608)
[error] org.trafodion.jdbc.t4.TrafT4Connection.<init>(TrafT4Connection.java:1561)
[error] org.trafodion.jdbc.t4.HPT4DataSource.getConnection(HPT4DataSource.java:129)
[error] org.trafodion.jdbc.t4.HPT4DataSource.getConnection(HPT4DataSource.java:173)
[error] org.trafodion.jdbc.t4.T4Driver.connect(T4Driver.java:183)
[error] doobie.free.drivermanager$$anon$2$$anonfun$apply$10.apply(drivermanager.scala:217)
[error] doobie.free.drivermanager$$anon$2$$anonfun$apply$10.apply(drivermanager.scala:217)
[error] com.db.doobie.TrafodionDBSpec.selectDataTest(DBTest.scala:120)
[error] com.db.doobie.TrafodionDBSpec$$anonfun$is$1$$anonfun$apply$4.apply(DBTest.scala:35)
[error] com.db.doobie.TrafodionDBSpec$$anonfun$is$1$$anonfun$apply$4.apply(DBTest.scala:35)

**Comment by tpolecat** [comment] 2015-08-28 14:28
Instance construction is explosively complex so I'm guessing scalac is just giving up. I'll see if there's a way to simplify.

**Comment by tpolecat** [comment] 2015-10-10 22:44
@milessabin Here is the example you were asking for. It is not doobie-specific, but this is the mechanism I'm using. Is there a better way to do this kind of thing now?

```scala
import shapeless._

class TC[A]

object TC extends ProductTypeClassCompanion[TC] {

  def apply[A](implicit ev: TC[A]) = ev

  implicit val IntTC: TC[Int] = new TC[Int]

  object typeClass extends ProductTypeClass[TC] {
    def product[H, T <: HList](H: TC[H], T: TC[T]): TC[H :: T] = new TC[H :: T]
    def emptyProduct: TC[HNil] = new TC[HNil]
    def project[F, G](instance: => TC[G], to: F => G, from: G => F): TC[F] = new TC[F]
  }

}
```

Some examples

```scala
// 32 is ok
TC[Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: 
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: 
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: 
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: HNil]

// 64 doesn't seem to terminate
TC[Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int ::
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: 
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: 
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: 
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: 
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: 
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: 
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: HNil]
```

**Comment by wedens** [comment] 2015-10-12 05:55
Works with `Generic` instead of `ProductTypeClassCompanion`:
```scala
import shapeless._

class TC[A]

object TC {

  def apply[A](implicit ev: TC[A]) = ev

  implicit val IntTC: TC[Int] = new TC[Int]

  implicit def deriveHNil: TC[HNil] = new TC[HNil]
  implicit def deriveHCons[H, T <: HList](implicit H: TC[H], T: TC[T]): TC[H :: T] = new TC[H :: T]
  implicit def deriveInstance[F, G](implicit gen: Generic.Aux[F, G], G: TC[G]): TC[F] = new TC[F]
}

object test {
  TC[Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int ::
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: 
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: 
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: 
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: 
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: 
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: 
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: HNil]
}
```
There was some other problem with `Generic` though #140

**Comment by wedens** [comment] 2015-10-12 05:59
And also it works with `ProductTypeClassCompanion` when you try to resolve instance in companion itself.

**Comment by tpolecat** [comment] 2015-10-12 13:53
Ok I will try that, thanks.

**Comment by tpolecat** [comment] 2015-10-12 13:53
The problem is with `Composite` obvs.

**Comment by tpolecat** [comment] 2015-10-13 04:37
@wedens your code above still diverges for me.

**Comment by wedens** [comment] 2015-10-13 04:43
@tpolecat hm. weird. which scala and shapeless version do you use?

**Comment by tpolecat** [comment] 2015-10-13 04:44
2.11.7 and 2.2.2

**Comment by wedens** [comment] 2015-10-13 04:46
@tpolecat same.. *exactly* this code diverges?

**Comment by tpolecat** [comment] 2015-10-13 04:48
Yes. Copy/Paste. Tried it from doobie sbt, both in the REPL and as a source file.

**Comment by wedens** [comment] 2015-10-13 04:53
Interesting. If I put this code in doobie, it diverges. In a separate project it compiles.

**Comment by tpolecat** [comment] 2015-10-13 04:55
![image](https://cloud.githubusercontent.com/assets/1200131/10445777/d6b20a20-712b-11e5-8d37-2467ca467e72.png)

**Comment by tpolecat** [comment] 2015-10-14 14:21
@wedens @milessabin @non ok this is nuts, but compilation doesn't terminate if you are using kind-projector. Code and relevant sbt nonsense reproduced here.

@wpoosanguansit if you are using kind-projector in your project can you remove it and see if it fixes your problem?

**build.sbt**

```scala
scalaVersion := "2.11.7"

libraryDependencies += "com.chuusai"  %% "shapeless" % "2.2.2"

// Comment this line out and hmm.scala compiles. With this line compilation doesn't terminate.
addCompilerPlugin("org.spire-math" % "kind-projector" % "0.6.3" cross CrossVersion.binary)
```

**hmm.scala**

```scala
import shapeless._

class TC[A]

object TC {

  def apply[A](implicit ev: TC[A]) = ev

  implicit val IntTC: TC[Int] = new TC[Int]

  implicit def deriveHNil: TC[HNil] = new TC[HNil]
  implicit def deriveHCons[H, T <: HList](implicit H: TC[H], T: TC[T]): TC[H :: T] = new TC[H :: T]
  // not required for this example
  implicit def deriveInstance[F, G](implicit gen: Generic.Aux[F, G], G: TC[G]): TC[F] = new TC[F]
}

object test {
  TC[Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int ::
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: 
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: 
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: 
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: 
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: 
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: 
   Int :: Int :: Int :: Int :: Int :: Int :: Int :: Int :: HNil]
}
```

**Comment by wedens** [comment] 2015-10-14 14:33
@tpolecat have you tried `ProductTypeClassCompanion` without KP?

**Comment by tpolecat** [comment] 2015-10-14 14:36
Nope. I have to step out for a while but I'll try it when I get back.

**Comment by non** [comment] 2015-10-14 15:52
Oh man. I'll look into this. Thanks and sorry! :sob:

**Comment by wpoosanguansit** [comment] 2015-10-14 15:54
@tpolecat I am not using that plugin at all.  But I am using others.  I will validate them to see if they play any role in this.

**Comment by milessabin** [comment] 2015-10-15 10:37
Are you able to try with shapeless 2.2.5 or 2.3.0-SNAPSHOT?

**Comment by wedens** [comment] 2015-10-15 10:51
@milessabin same problem with 2.2.5 and 2.3.0-SNAPSHOT

**Comment by milessabin** [comment] 2015-10-15 10:59
@tpolecat did you explore the avenue that @wedens suggested here: https://github.com/tpolecat/doobie/issues/217#issuecomment-147297597 ... ie. using `Lazy` and implicit resolution directly rather than using `ProductTypeClass`?

**Comment by non** [comment] 2015-10-15 11:55
I think any compiler plugin that uses a `TypingTransformer` will have this problem -- it looks to me like parsing these nested hlist types has a quadratic time complexity (at least, that's what I obseved via tracing).

The solution for *kind-projector* involves memoizing the `Tree => Tree` transformation (using a cache). My sense is that other compiler plugins could solve this problem the same way, but there doesn't seem to be a "standard way" to do this.

**Comment by non** [comment] 2015-10-15 12:36
Fixed by https://github.com/non/kind-projector/pull/22 -- @tpolecat I'll push a new release ASAP.

**Comment by milessabin** [comment] 2015-10-15 12:48
:clap:

**Comment by non** [comment] 2015-10-15 12:48
If you upgrade to kind-projector 0.7.1 the example should compile correctly now.

**Comment by tpolecat** [comment] 2015-10-15 16:57
@non Awesome! This fixes the direct implicit resolution (without `ProductTypeclass`) which I think is now working thanks to `Lazy` (thanks @milessabin for mentioning it). I'll do some more testing tonight but I think all is well!

**Closed** 2015-10-16 04:40 UTC
