### ISSUE TITLE
log handler doesn't log insert statements when using "withUniqueGeneratedKeys"

### ISSUE THREAD

**Issue by scuddalo** [tpolecat/doobie#604] opened 2017-09-22 18:31 UTC
When I run `sqlFragment.update.withUniqueGeneratedKeys` I don't see the insert statement in my log.  When I simply do `sqlFragment.update.run`, I see the insert statements in the log. 

I am using version 0.4.4 and my log handler looks like this: https://gist.github.com/scuddalo/180bc937f8b4f71e598d1e623e236502

my update function looks like this:

```scala
  override def perform(input: Client) = sql"""
    insert into di_client (client_id, created, last_modified, name)
    values (${input.id}, ${input.created}, ${input.lastModified}, ${input.name})
  """.asInstanceOf[Fragment]
    .update(logHandler)
    .withUniqueGeneratedKeys("client_id")
```

**Comment by Arcovion** [comment] 2017-09-23 04:37
Duplicate of https://github.com/tpolecat/doobie/issues/533

**Comment by jatcwang** [comment] 2023-09-19 09:52
I think this is no longer a problem. I see that joesan was able to see his query logged too :)
https://discord.com/channels/632277896739946517/632727524434247691/1153572905117032470

**Closed by jatcwang** 2023-09-19 09:52 UTC
