### ISSUE TITLE
outer joins and nullability?

### ISSUE THREAD

**Issue by refried** [tpolecat/doobie#177] opened 2015-06-18 03:02 UTC
in Intellij + H2,
```sql
create table b (
  id integer auto_increment primary key not null,
  field integer not null
);
create table a (
  id integer auto_increment primary key not null,
  b integer default null,
  foreign key (b) references b (id)
);
insert into a values ();
select a.id, b.field from A left join B on a.b = b.id;
```
yields:
`id: 1, field: null`

but doobie 0.2.2 gives a warning and an empty result set: 
```scala
val q = sql"select a.id, b.field from A left join B on a.b = b.id;".query[(Int,Option[Int])]
q.check.run
```
yields
```
select a.id, b.field from A left join B on a.b = b.id;
✓ SQL Compiles and Typechecks
✓ C01 ID    INTEGER (INTEGER) NOT NULL  →  Int
✕ C02 FIELD INTEGER (INTEGER) NOT NULL  →  Option[Int]
  - Non-nullable column FIELD is unnecessarily mapped to an Option type.
```
and
```scala
q.list.quick.run
```
yields
```scala
List()
```

`field` is non-nullable but `b.field from a left join b on a.b = b.id` is nullable when `a.b` is nullable.

**Comment by tpolecat** [comment] 2015-06-18 03:19
The metadata thing is related to #164.

I do not get an empty resultset. Code I'm running is:

```scala
package doobie.example

import scalaz._, Scalaz._
import scalaz.effect.{ SafeApp, IO }
import scalaz.stream.Process

import doobie.imports._

object Arya extends SafeApp {

  val db = DriverManagerTransactor[IO]("org.h2.Driver", "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1", "sa", "")

  val create = 
    sql"""

      create table b (
        id integer auto_increment primary key not null,
        field integer not null
      );

      create table a (
        id integer auto_increment primary key not null,
        b integer default null,
        foreign key (b) references b (id)
      );

      insert into a values ();

    """.update

  val query = 
    sql"select a.id, b.field from A left join B on a.b = b.id;".query[(Int,Option[Int])]

  override def runc: IO[Unit] =
    (create.run *> query.list).transact(db) >>= (x => IO.putStrLn(x.toString))

  // [info] Running doobie.example.Arya 
  // List((1,None))

}
```

**Comment by refried** [comment] 2015-06-18 15:14
Your program gives the right results for me too.  It's possible that I had "automatic db commits" disabled in intellij, and maybe that's why intellij was able to select the row (same transaction?) when doobie wasn't.  Haven't had a chance to test that theory yet.

I guess per #164, the nullability metadata comes from jdbc and can't be smart about situations like this?

**Comment by tpolecat** [comment] 2015-06-18 18:58
Ok. I'm going to close this as a duplicate of #164 … feel free to reopen if you think I missed something.

**Closed by tpolecat** 2015-06-18 18:58 UTC
