### ISSUE TITLE
illegal cyclic reference

### ISSUE THREAD

**Issue by netanelrabinowitz** [tpolecat/doobie#598] opened 2017-09-13 09:02 UTC
I'm trying to do a simple select into a list of some custom class. my problem is that the class is annotated with Kryo field serializer like this: 

```
final case class InstallLog(@(Tag@field)(10) logTime: LocalDateTime,
                            @(Tag@field)(11) eventTime: LocalDateTime,
                            @(Tag@field)(12) recTime: Option[LocalDateTime], ...
```

I'm getting an illegal cyclic reference error, I know this is a kryo problem but I really need some workaround to this issue. I can't simply get rid of this annotations.
Thanks a lot!

```
error reading Scala signature of entities.ProductId: illegal cyclic reference involving object FieldSerializer
java.lang.RuntimeException: error reading Scala signature of entities.PrtProductId: illegal cyclic reference involving object FieldSerializer
    at scala.reflect.internal.pickling.UnPickler.unpickle(UnPickler.scala:44)
    at scala.reflect.runtime.JavaMirrors$JavaMirror.unpickleClass(JavaMirrors.scala:619)
    at scala.reflect.runtime.SymbolLoaders$TopClassCompleter.$anonfun$complete$2(SymbolLoaders.scala:25)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
    at scala.reflect.internal.SymbolTable.slowButSafeEnteringPhaseNotLaterThan(SymbolTable.scala:236)
    at scala.reflect.runtime.SymbolLoaders$TopClassCompleter.complete(SymbolLoaders.scala:22)
    at scala.reflect.runtime.SymbolLoaders$TopClassCompleter.load(SymbolLoaders.scala:30)
    at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.$anonfun$typeParams$1(SynchronizedSymbols.scala:142)
    at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:125)
    at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.gilSynchronizedIfNotThreadsafe$(SynchronizedSymbols.scala:121)
    at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$7.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:170)
    at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.typeParams(SynchronizedSymbols.scala:135)
    at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.typeParams$(SynchronizedSymbols.scala:134)
    at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$7.typeParams(SynchronizedSymbols.scala:170)
    at scala.reflect.internal.Types$NoArgsTypeRef.typeParams(Types.scala:1916)
    at scala.reflect.internal.Definitions$DefinitionsClass.fullyInitializeType(Definitions.scala:212)
    at scala.reflect.internal.Types$Type.toString(Types.scala:938)
    at doobie.util.meta$Meta$$anon$1.<init>(meta.scala:209)
    at doobie.util.meta$Meta$.basic(meta.scala:208)
    at doobie.util.meta$Meta$$anon$1.xmap(meta.scala:216)
    at doobie.util.meta$LowPriorityImplicits.unaryProductMetaNonNullable(meta.scala:354)
    at doobie.util.meta$LowPriorityImplicits.unaryProductMetaNonNullable$(meta.scala:349)
    at doobie.util.meta$Meta$.unaryProductMetaNonNullable(meta.scala:154)
    at events.recovery.EventLogDaoSpec$anon$generic$macro$178$1.inst$macro$153$lzycompute(EventLogDaoSpec.scala:48)
    at events.recovery.EventLogDaoSpec$anon$generic$macro$178$1.inst$macro$153(EventLogDaoSpec.scala:48)
    at events.recovery.EventLogDaoSpec.$anonfun$new$4(EventLogDaoSpec.scala:48)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
```

**Comment by tpolecat** [comment] 2017-09-18 05:47
I really have no idea. `Meta` is asking for the name of its type argument via a `TypeTag` and it appears that the Kryo-annotated class has a bogus signature.

```scala
scala> import scala.reflect.runtime.universe.TypeTag
import scala.reflect.runtime.universe.TypeTag

scala> implicitly[TypeTag[List[Int]]].tpe.toString
res1: String = scala.List[Int]
```

Try that, but with `PrtProductId` instead of `List[Int]` and see what happens. It looks like the issue is with that class.

**Comment by NetanelRabinowitz** [comment] 2017-09-20 06:55
yeah, basically every class with the Kryo field serialized annotation will throw an exception if I try to get my hands on the TypeTag. 

```
scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving object FieldSerializer
	at scala.reflect.internal.Symbols$Symbol.$anonfun$info$3(Symbols.scala:1500)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.reflect.internal.Symbols$Symbol.lock(Symbols.scala:555)
```

do know if there is any way to strip the annotation at runtime?

**Comment by tpolecat** [comment] 2017-09-20 16:14
> do know if there is any way to strip the annotations at runtime?

I don't know of an easy way … I think you would need to rewrite the bytecode. But I think Kryo uses these annotations at runtime to figure out how to serialize things, in which case deleting them from bytecode would be equivalent to deleting them from source code.

My guess is that it's a limitation of the Scala unpickler, although it could also be a bug in Kryo. If you have a minimal reproducible example I encourage you to add it to https://github.com/scala/bug/issues/10129 which appears to be related.

The irony is that doobie only uses this tag when typechecking queries, so it's not strictly necessary; but it makes a big difference when you're trying to diagnose inconsistencies between your SQL statements and the underlying schema.

**Comment by NetanelRabinowitz** [comment] 2017-10-31 22:37
Sorry for the late response. 
The only ways I can think of to work around this issue right now are creating a duplicate case class free from annotation and map the query result. Obviously this is not what I want to do as it requires tons of boilerplate, and feel very stupid :) or I can maybe use the generic representation of the annotated case class. I can live with that as it requires almost zero boilerplate code. 

The thing is that I can make it work only for one level deep case class. if my case class has got another case class as one of its fields, I will experience the same problem we begin with.
I know there is a way to extract an hlist of hlists for nested case class like this, I tried to play with @milessabin example of [DeepHlister](https://github.com/milessabin/shapeless/blob/master/examples/src/main/scala/shapeless/examples/deephlister.scala) but I do not quite understand how to extract the repr and hand it to doobie.

here is for example a one level case class example.

`    
val flattenGen = Generic[Whatever] // generic of flatten case class
val a = HC.createStatement(HS.executeQuery("select * from athenaWhatever")(HRS.list[flattenGen.Repr]))
      .transact(xa)
      .unsafePerformIO

`

This is working just fine.
any Idea how can I do a similar thing with a nested case class? 
Thanks a lot!

**Comment by jatcwang** [comment] 2024-05-29 19:36
I'm going to close this ticket as this feels somewhat niche and doesn't seem to be an issue with doobie. LMK if you think otherwise :)

**Closed by jatcwang** 2024-05-29 19:36 UTC
