### ISSUE TITLE
sql" interpolator is not recognized by IntelliJ

### ISSUE THREAD

**Issue by sLite** [tpolecat/doobie#206] opened 2015-07-31 19:45 UTC
Highlighting and typechecking is broken for the sql" interpolator. I'm not experienced enough to give the fix a shot though.

@Jacoby6000 came up with this fix:

```
implicit class SqlIdeFixer(sc: StringContext) extends doobie.syntax.string.SqlInterpolator(sc) {
  def sql2[A: Composite](args: A) = this.sql.applyProduct(args)
}
```

**Comment by Jacoby6000** [comment] 2015-07-31 20:38
I use this by having a support class containing the implementation:

```scala
object DoobieSupport {
    // Meta mappings and such

    implicit class SqlIdeFixer(sc: StringContext) extends doobie.syntax.string.SqlInterpolator(sc) {
        def sql2[A: Composite](args: A) = this.sql.applyProduct(args)
    }
}
```

Then in classes where you use sql you just

```scala
import path.to.package.DoobieSupport._
```

and instead of using the sql string interpolator you use sql2:
```
    val sqlStatement = sql2"select foo from bar"
```

**Comment by tpolecat** [comment] 2015-07-31 20:40
So the only thing you did was add a layer of indirection? Interesting.

**Comment by Jacoby6000** [comment] 2015-07-31 20:43
Pretty much.  The ide can understand direct conversions to String contexts, like this. But with yours, where the sql interpolator is nested within the object created by your implicit conversion, it doesn't understand.

**Comment by tpolecat** [comment] 2015-08-07 22:59
The above suggestions don't work; you need `applyProduct` to abstract over arity. I'm moving this to backlog because I don't really care about making IDEA happy. If someone wants to submit a PR I will look at it.

**Comment by guersam** [comment] 2016-03-28 12:18
Opened https://youtrack.jetbrains.com/issue/SCL-10091 with a simplified example as I'm suffering from this either. Please vote!

**Comment by guersam** [comment] 2016-03-28 12:24
But I'm not sure if IDEA will infer the return type as well even after the issue is resolved, because `applyProduct` is a macro.

**Comment by tpolecat** [comment] 2016-03-28 22:03
@guersam thanks for doing this. I tend to ignore IntelliJ but it will be nice to get it fixed if they feel like doing it.

**Comment by jedesah** [comment] 2016-06-10 17:03
I tend to use IntelliJ, I am unfortunately unaware of a less crappy development environment for Scala (not trying to bash IntelliJ or any other development tool, supporting the entirety of Scala is REALLY hard).

That said. I don't think `doobie` should add cruft to make IntelliJ (or any other editor) happy. Thx @guersam for opening an issue on YouTrack where the proper fix lies.

**Comment by Jacoby6000** [comment] 2016-06-10 20:11
@jedesah ensime + atom/emacs/vs-code/vim has been working really well for me.

**Comment by ibalashov** [comment] 2016-07-07 12:25
Trying to apply the fix, but getting the following error:

> Error:(8, 48) inferred type arguments [A] do not conform to method applyProduct's type parameter bounds [A <: shapeless.HList]
>    def sql2[A: Composite](args: A) = this.sql.applyProduct(args)

**Comment by tpolecat** [comment] 2016-07-07 16:34
@ibalashov if you want to see if it's working try something like `def foo(n:Int, s:String) = sql"blah $n $s"` which will desugar to `SqlInterpolator(...).applyProduct(b :: a :: HNil)`.

**Comment by clayrat** [comment] 2016-07-13 12:49
So, the https://confluence.jetbrains.com/display/SCA/Scala+Plugin+EAP+15 says that the SCL-10091 fix is included starting from `2016.2.0`, but it doesn't seem to work for me, can somebody confirm?

**Comment by ibalashov** [comment] 2016-07-13 13:49
@clayrat Didn't work for me either.

**Comment by KadekM** [comment] 2016-07-18 21:02
Even with nightly plugin build problem is still there in IntelliJ 2016.2

**Comment by denisftw** [comment] 2016-08-30 17:39
Apparently, they fixed the issue opened by @guersam, and indeed, in the latest version of the Scala plugin his simplified example works without red highlighting. This doesn't, however, fix the problem with sql interpolation in doobie. Looks like the real use case is slightly more involved than `DynamicInterpolationExample`.

**Comment by tpolecat** [comment] 2016-08-31 06:45
@denisftw hm, ok. Thanks for the info. Guess we need a more involved use case to report.

**Comment by dvic** [comment] 2017-01-17 14:08
I have made available a repo that demonstrates the problem: https://github.com/dvic/intellij-interpolator-issue. I have also submitted a new issue: https://youtrack.jetbrains.com/issue/SCL-11258.

**Comment by slouc** [comment] 2017-02-24 16:57
@ibalashov Did you ever resolve your problem

> inferred type arguments [A] do not conform to method applyProduct's type parameter bounds [A <: shapeless.HList]

**Comment by Ma27** [comment] 2017-03-26 08:19
the current workaround (I know it's a hack, but at least it ensures IntelliJ understands what I'm doing) with `0.4.1` I use looks like this:

``` scala
import doobie.imports._

// ...
sql"LONG SQL QUERY".asInstanceOf[Fragment].update
```

**Comment by od0** [comment] 2017-03-26 16:59
another option that works reasonably well- 
```
val query: Query0[Long] = sql"""
  SELECT id FROM foo WHERE bar=$baz
  """.query[Long]

query.vector.flatMap ...
```
IntelliJ will still be confused on `.query[Long]` but every subsequent operation on `query` will have full type interpretation. I actually kind of like explicitly defining the query string before beginning operations on it, particularly as queries and logic become more complex.

**Comment by Jacoby6000** [comment] 2017-03-29 16:53
I believe the root cause of this not working is that the `sql` interpolator (and other fragment interpolators) use the `applyProduct` method, provided by shapeless' `ProductArgs` class.  This causes many apply methods to be generated, and I think Intellij is not witnessing the creation of these apply methods.  You could probably create an intellij plugin to fix it.  I started an attempt [here](https://github.com/Jacoby6000/intellij-shapeless-macro-support/blob/master/src/main/scala/com/jacoby6000/shapeless/injector/ShapelessApplyProductInjector.scala) awhile back.  

An alternative would be to just create an interpolator with a ton of overloaded apply methods and defer to the `applyProduct` provided by doobie.  I've used these "IDE Helper" type methods before with enough success to satisfy my taste.

**Comment by Daenyth** [comment] 2017-03-29 16:56
@Jacoby6000 yes, see the comment above (https://github.com/tpolecat/doobie/issues/206#issuecomment-273171000) and the associated upstream bug ticket about this

**Comment by Jacoby6000** [comment] 2017-03-29 17:25
Ah, my apologies.  I briefly looked over this comment thread and didn't see any mentions of `ProductArgs` in the comment chain and assumed it hadn't been talked about.

**Comment by tejasmanohar** [comment] 2017-04-08 05:10
Here's an extension of @od0's hack that doesn't require as much code pollution.
```
private object Query0Hack {
  implicit def query0AsFragment[T](q: Query0[T]): Fragment = {
    q.asInstanceOf[Fragment]
  }
}
```

**Comment by tpolecat** [comment] 2017-04-08 05:11
That doesn't look right. `Query0` is not a fragment. It *has* a fragment though.

**Comment by tejasmanohar** [comment] 2017-04-08 05:49
Oh strange, not using it currently. Maybe, I fooled IntelliJ but not `scala` itself.

**Comment by LoranceChen** [comment] 2018-01-19 08:55
typelevel library almostly has the problem in idea. such as <+> operation in cats when I use http4s library.

**Comment by LoranceChen** [comment] 2018-01-19 09:28
it seems fixed at Build 2017.3.825 in here: https://confluence.jetbrains.com/display/SCA/Scala+Plugin+Nightly

**Comment by daviswahl** [comment] 2018-01-23 20:35
Looks fixed in release too. Very exciting!

**Comment by tpolecat** [comment] 2018-01-23 21:32
Great, thanks all. I would take a PR updating the FAQ. Leaving open pending that.

**Comment by unoexperto** [comment] 2018-01-24 05:18
I still red for me for `List[ConnectionIO].sequence` calls but better than before for sure.

**Comment by Jacoby6000** [comment] 2018-01-24 15:53
@unoexperto That would be unrelated to the sql interpolator, and is just general intellij badness

**Comment by schmitch** [comment] 2018-03-28 18:03
@tpolecat  Actually since at least IntelliJ 2017.2 and 2018.1 this looks working now.
(IntelliJ 2018.1 has parameter type hints, which can't detect the type of sql"") however everything else, autocompletion, etc. just works

**Comment by tpolecat** [comment] 2018-03-28 18:17
Thanks. I'll close this.

**Closed by tpolecat** 2018-03-28 18:17 UTC
