### ISSUE TITLE
Connection leakage as discussed in Gitter / testcase

### ISSUE THREAD

**Issue by Dennis4b** [tpolecat/doobie#787] opened 2018-10-19 11:31 UTC
As discussed in Gitter, found a way to reproduce the "idle in transaction" lost connections.
Hopefully self explanatory:
```scala
package test

import cats._, cats.data._, cats.implicits._, cats.effect._
import doobie._, doobie.implicits._
import doobie.hikari._, doobie.hikari.implicits._

object stresstest {
    def run(xa: HikariTransactor[IO])(implicit cs: ContextShift[IO]): IO[Unit] = {
        val task = sql"""                                                                                                            
            select 'result' from pg_sleep(0.1)
            """.query[String].unique.transact(xa).flatMap(result => IO {
            /* Note, this will throw an exception, see the "attempt" below */
            java.nio.file.Files.size(java.nio.file.Paths.get("/nonexistingfile"))
        })

        (0 until 100).map(_ => (0 until 8).map(_ => task).toList.parSequence.attempt.map(_ => ()) ).toList.sequence.map(_ => ())
    }
}
```

**Comment by lysebraate** [comment] 2018-12-12 15:18
I think we are hitting this in production. The symptoms are very similar with lots of `idle in transaction` states in PG. Reproducing it is somewhat more difficult.

We have done some testing with the example @Dennis4b gave. We can reproduce the behaviour with fewer concurrent threads than 100. We did a test with `setMaximumPoolSize` to 1 and `connectEC` to size 1 and `transactEC` to fixed size 4. With 2 x 4 `task`s constructed we can see this:

1. first 4 IOs are trying to get a connection, four threads are created in transact pool - one thread marked as `Running`
2. Fist IO gets a connection - connect pool thread marked as `Park` (`pg_sleep` in our case)
3. First IO execute `before` and `after` per Strategy
4. First IO releases connection - `always`
5. Second IO gets a connection - (connect pool thread still marked as `Park` which I guess is a good thing, reusing connection) a new thread in transact pool starts `Running` while the previous is marked as `Park`.
6. Second IO executes `before`

Somewhere between 5-6 the exception from the first IO bubbles up resulting in only `Parked` threads in the `connectEC` and `transactEC` pools.
We can verify that the Second IO is the one idling by looking at `pg_stat_activity` (sql comment with thread "identifier").

```
postgres@localhost:postgres> select * from pg_stat_activity where application_name ilike 'PostgreSQL%'
+---------+-----------+-------+------------+-----------+------------------------+---------------+-------------------+---------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+-------------------+--------------+---------+---------------+----------------+---------------------------------------------+----------------+
| datid   | datname   | pid   | usesysid   | usename   | application_name       | client_addr   | client_hostname   | client_port   | backend_start                 | xact_start                    | query_start                   | state_change                  | wait_event_type   | wait_event   | state   | backend_xid   | backend_xmin   | query                                       | backend_type   |
|---------+-----------+-------+------------+-----------+------------------------+---------------+-------------------+---------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+-------------------+--------------+---------+---------------+----------------+---------------------------------------------+----------------|
| 12994   | postgres  | 2142  | 10         | postgres  | PostgreSQL JDBC Driver | 172.17.0.1    | <null>            | 52246         | 2018-12-12 11:45:37.315731+00 | 2018-12-12 11:45:37.426879+00 | 2018-12-12 11:45:37.427288+00 | 2018-12-12 11:45:37.427296+00 | Timeout           | PgSleep      | active  | <null>        | 556            | /* 0:0 */ select 'result' from pg_sleep(10) | client backend |
+---------+-----------+-------+------------+-----------+------------------------+---------------+-------------------+---------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+-------------------+--------------+---------+---------------+----------------+---------------------------------------------+----------------+
SELECT 1
Time: 0.009s
postgres@localhost:postgres> select * from pg_stat_activity where application_name ilike 'PostgreSQL%'
+---------+-----------+-------+------------+-----------+------------------------+---------------+-------------------+---------------+-------------------------------+-------------------------------+-------------------------------+------------------------------+-------------------+--------------+---------+---------------+----------------+---------------------------------------------+----------------+
| datid   | datname   | pid   | usesysid   | usename   | application_name       | client_addr   | client_hostname   | client_port   | backend_start                 | xact_start                    | query_start                   | state_change                 | wait_event_type   | wait_event   | state   | backend_xid   | backend_xmin   | query                                       | backend_type   |
|---------+-----------+-------+------------+-----------+------------------------+---------------+-------------------+---------------+-------------------------------+-------------------------------+-------------------------------+------------------------------+-------------------+--------------+---------+---------------+----------------+---------------------------------------------+----------------|
| 12994   | postgres  | 2142  | 10         | postgres  | PostgreSQL JDBC Driver | 172.17.0.1    | <null>            | 52246         | 2018-12-12 11:45:37.315731+00 | 2018-12-12 11:45:47.484216+00 | 2018-12-12 11:45:47.484432+00 | 2018-12-12 11:45:47.48444+00 | Timeout           | PgSleep      | active  | <null>        | 556            | /* 0:1 */ select 'result' from pg_sleep(10) | client backend |
+---------+-----------+-------+------------+-----------+------------------------+---------------+-------------------+---------------+-------------------------------+-------------------------------+-------------------------------+------------------------------+-------------------+--------------+---------+---------------+----------------+---------------------------------------------+----------------+
SELECT 1
Time: 0.009s
postgres@localhost:postgres> select * from pg_stat_activity where application_name ilike 'PostgreSQL%'
+---------+-----------+-------+------------+-----------+------------------------+---------------+-------------------+---------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+-------------------+--------------+---------------------+---------------+----------------+---------------------------------------------+----------------+
| datid   | datname   | pid   | usesysid   | usename   | application_name       | client_addr   | client_hostname   | client_port   | backend_start                 | xact_start                    | query_start                   | state_change                  | wait_event_type   | wait_event   | state               | backend_xid   | backend_xmin   | query                                       | backend_type   |
|---------+-----------+-------+------------+-----------+------------------------+---------------+-------------------+---------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+-------------------+--------------+---------------------+---------------+----------------+---------------------------------------------+----------------|
| 12994   | postgres  | 2142  | 10         | postgres  | PostgreSQL JDBC Driver | 172.17.0.1    | <null>            | 52246         | 2018-12-12 11:45:37.315731+00 | 2018-12-12 11:45:47.484216+00 | 2018-12-12 11:45:47.484432+00 | 2018-12-12 11:45:57.486629+00 | Client            | ClientRead   | idle in transaction | <null>        | 556            | /* 0:1 */ select 'result' from pg_sleep(10) | client backend |
+---------+-----------+-------+------------+-----------+------------------------+---------------+-------------------+---------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+-------------------+--------------+---------------------+---------------+----------------+---------------------------------------------+----------------+
```

If we choose to handle the error on each IO the connection is closed as expected:
```
.map(u => task)
.toList
.map(s => s.handleErrorWith(_ => IO.pure[Long](1L)))
.parSequence
```

If we `Thread.sleep` inside the `task` so that every parallel task is done with their db operation the connection is also closed as expected. 

Current stack is:
* doobie 0.6.0
* hikari 3.2.0
* fs2 1.0.0
* cats 1.4.0
* cats-effect 1.0.0
* http4s 0.20.0-M2

We have also tried this with Tomcat JDBC pool with the same result as above.

I am currently debugging this with @freekh. He might have new/other insight as well.

![halts](https://raw.githubusercontent.com/lysebraate/screenshots/master/halts.png)
![works](https://raw.githubusercontent.com/lysebraate/screenshots/master/works.png)

**Comment by tpolecat** [comment] 2019-01-16 00:44
Yep this is fixed by #823. I'll back-port and do a release.

**Comment by tpolecat** [comment] 2019-01-17 22:09
Turns out I can't backport to 0.6.x because it breaks bincompat. Can you guys try 0.7.0-M2 (currently trickling up to Sonatype, if it's not there wait a bit and try again) and see if it resolves the issue for you? There are no other significant changes relative to 0.6.0

**Comment by lysebraate** [comment] 2019-01-18 12:50
Unable to reproduce with 0.7.0-M2. Nice work. Thank you!

**Comment by tbrown1979** [comment] 2019-03-06 22:38
@tpolecat Do you happen to know which part of that fix breaks binary compat? I was wondering if maybe a subset of it could be back-ported?

**Comment by tpolecat** [comment] 2019-03-06 22:43
`cio.transact(xa)` takes `Monad[M]` in 0.6 and `Bracket[M, Throwable]` in 0.7 and I don't see an obvious way around it, but if you figure something out I would take a PR.

**Comment by tbrown1979** [comment] 2019-03-06 23:49
@tpolecat Thanks for the quick response 😄

**Comment by tbrown1979** [comment] 2019-03-07 00:01
Would it be possible to back-port essentially the same PR, but leave `transact` the same but introduce a `transactB` that has the `Bracket` constraint? I know that's not ideal, but it provides a method that will prevent the idle transactions. Lemme know what you think!

**Comment by tpolecat** [comment] 2019-03-07 00:04
If you're recompiling anyway I suggest just moving to 0.7.0-M3 if you can. I'd like to get it out soon and there are no [new] issues that I know of.

**Comment by tbrown1979** [comment] 2019-03-07 00:12
There was some hesitation on wanting to upgrade to `0.7.0-Mx` just yet, but maybe that's what we'll do. Thanks!

**Comment by jatcwang** [comment] 2024-08-05 09:13
This is probably no longer relevant given CE3.

**Closed by jatcwang** 2024-08-05 09:13 UTC
