### ISSUE TITLE
Allow splicing literal values in sql interpolator

### ISSUE THREAD

**Issue by ramnivas** [tpolecat/doobie#189] opened 2015-07-14 03:12 UTC
I have a use case, where I need to abstract over table name (something along the following lines: ```sql"""select count(*) from $tableName"""```. However, this doesn't currently work in Dooble, since the table name will be passed to the underlying prepared statement (which then will be escaped by the JDBC driver).

Slick provides a way to pass unescaped value in their sql interpolator [1]. I wonder if Dooble can do the same.

[1] http://slick.typesafe.com/doc/3.0.0/sql.html#splicing-literal-values

**Comment by tpolecat** [comment] 2015-07-14 04:12
Hi, yes, this is a common question. In this case you can do what you want by constructing a `Query0` explicitly:

```scala
scala> def sql(table: String) = s"select count(*) from $table"
sql: (table: String)String

scala> Query0[Int](sql("country"), None).unique.transact(xa).run
res1: Int = 239
```

If your query takes parameters you need to construct a `Query` as demonstrated in the gist associated with #156. I'm closing this as a duplicate of that issue. Please feel free to add comments or questions there. Thanks!

**Closed by tpolecat** 2015-07-14 04:12 UTC

**Comment by ramnivas** [comment] 2015-07-14 04:18
This works! Thanks for your quick response. 

It will be nice to have this info somewhere in the book of doobie (I saw the last section of http://tpolecat.github.io/doobie-0.2.2/04-Selecting.html, but couldn't quite manage to translate it for my use case).

p.s. Just started using Doobie and I like what I have seen so far.
